# 6.identity operator
# a=100
# b=100
# print(id(a))
# print(id(b))
# print(a is b)
# conditional Statment
# a=" "
# if a:
#     print("yes")
# else:
#     print("NO")    
# if 1*1*0:
#    print("Yes")
# else:
#     print("NO")     
# Wap to check number given by user in add or even
# num=23
# if num%2==0:
#  print("Even number")
# else: 
#   print("odd Number")

# write a program to print the last digit of a number
# Num1=456735
# print("Last Digit", Num1%10)
# num1=31
# num2=9
# num3=12

# wap to find largest
# if num1>=num2 and num1>=num3:
#     print(f"{num1} is largest number")
# elif num2>=num1 and num2>=num3:
#     print(f"{num2} is largest Number")
# else: 
#     num3>=num1 and num3>=num2
#     print(f"{num3} is Largest Numer")       
# wap to find Smallest
# if num1<=num2 and num1<=num3:
#     print(f"{num1} is Smallest number")
# elif num2<=num1 and num2<=num3:
#     print(f"{num2} is Smallest")
# else: 
#     num3<=num1 and num3<=num2
#     print(f"{num3} is Smallest Numer")
# n=100
# if n>50:
#  print("yest1")
# elif n>60:
#     print("Yes2")
# elif n>70:
#     print("Yes3")          